### ISSUE TITLE
P flag appears regardless of current branch

### ISSUE THREAD

**Issue by chrisb87** [jcgoble3/gitstuff#3]
The P flag appears when any local branches exist with commits that don't exist upstream. Ideally this would only apply to the current branch.

**Comment by jcgoble3** [comment]
> The P flag appears when any local branches exist with commits that don't exist upstream.

This is exactly my intent. It's a reminder that you have unpushed changes somewhere and could lose your work if something happens (e.g. hard drive failure). If you prefer it to apply only to the current branch, feel free to tweak it on your end to do so. I don't pretend to know enough about Git to have any idea how that would be done.

If you do get it working, I'd be happy to take a look at it. While I won't merge directly into the main code, I'd be willing to discuss the matter and show how to tweak it in the readme.

**Comment by chrisb87** [comment]
That makes sense, you're wanting to know if there's anything local that isn't backed up. With my workflow I only want to know about the current branch, so I changed that command to `git status -sb|grep -E "\[ahead .+\]")`

I also added a color for that state. Feel free to use as you wish!
https://gist.github.com/chrisb87/f72b1545efb6d5d4290b4ac39d6d883b

**Comment by jcgoble3** [comment]
Looks good. I'm on vacation right now and thus on my phone, but I'll add something to the readme when I get home to my laptop in a couple of days.

**Comment by jcgoble3** [comment]
I've now added two commits. The first is a note in the readme mentioning how to limit the `P` flag to the current branch. The color for unpushed commits is actually something that, while experimenting with it, I found useful for my own workflow, so I merged it directly into the main code in the second commit.

Look good to you?

**Comment by chrisb87** [comment]
Looks good to me!

**Comment by jcgoble3** [comment]
Great, thanks for the suggestion and code! :)
